AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Naming/FileName:
  Exclude:
    - 'test/acceptance/Vagrantfile'
